apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simplereact-backend.fullname" . }}-secrets
  labels:
    {{- include "simplereact-backend.labels" . | nindent 4 }}
type: Opaque
data:
  jwtKey: {{ .Values.secrets.jwtKey | default (randAlphaNum 32) | b64enc }}
  connectionString: {{ .Values.secrets.connectionString | default "Data Source=SimpleReact.db" | b64enc }}
