{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simplereact-observability.fullname" . }}-jaeger
  labels:
    {{- include "simplereact-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
spec:
  type: {{ .Values.jaeger.service.type }}
  ports:
    {{- range .Values.jaeger.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .name }}
    {{- end }}
  selector:
    {{- include "simplereact-observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
{{- end }}
